all:
	go run . --machine --interfaces --pins --matrix `tinygo targets`

machine:
	go run . --machine `tinygo targets`

interfaces:
	go run . --interfaces `tinygo targets`

pins:
	go run . --pins `tinygo targets`

matrix:
	go run . --matrix `tinygo targets`

help:
	go run . --help
