
DEVICES = \
    pca10040 \
    microbit \
    nrf52840-mdk \
    pca10031 \
    bluepill \
    reelboard \
    reelboard \
    pca10056 \
    pca10056 \
    itsybitsy-m0 \
    feather-m0 \
    trinket-m0 \
    circuitplay-express \
    stm32f4disco \
    stm32f4disco \
    circuitplay-express \
    gameboy-advance \
    itsybitsy-m4 \
    nucleo-f103rb \
    hifive1b \
    pinetime-devkit0 \
    x9pro

all:
	go run . $(DEVICES)


#all:
#	go run . pca10040 > ../content/doc/pca10040/machine.md
#	go run . hifive1b > ../content/doc/hifive1b/machine.md
#	go run . bluepill > ../content/doc/bluepill/machine.md
#	go run . gameboy-advance > ../content/doc/gameboy-advance/machine.md
#
